import Head from "next/head";
import { Image, HStack } from "@chakra-ui/react";
import Product from "../components/Product";
import { Image as NextImage } from "next/image";
import { useCartContext } from "../context/cartContext";
import { useEffect } from "react";

const products = [
  {
    imageUrl: "/samsung.webp",
    productName: "Samsung S20",
    price: 1100,
    id: "1",
  },
  {
    imageUrl: "/xiaomi.png",
    productName: "Xiaomi Poco F3",
    price: 600,
    id: "2",
  },
  {
    imageUrl: "/iphone.png",
    productName: "Iphone 12 Black",
    price: 1200,
    id: "3",
  },
];

export default function Home() {
  const { setCart } = useCartContext();
  useEffect(() => {
    setCart(JSON.parse(localStorage.getItem("cart") || "[]"));
  }, []);
  return (
    <div>
      <Head>
        <title> Create Next App </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Image
          as={NextImage}
          mb={4}
          w="full"
          h={270}
          fit="cover"
          src="/hero.jpg"
        />
        <HStack spacing={8} direction="row" p={2}>
          {products.map((product, index) => {
            return <Product {...product} key={index} />;
          })}
        </HStack>
      </>
    </div>
  );
}
